id = "jq"
name = "jq"
version = "0.0.2"
schema_version = 1
authors = ["Dang Huynh"]
description = "jq language support for Zed"
repository = "https://github.com/dangh/zed-jq"

[grammars.jq]
repository = "https://github.com/flurie/tree-sitter-jq"
commit = "c204e36d2c3c6fce1f57950b12cabcc24e5cc4d9"
